name: ikc_mobile_flutter
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.4+4

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  intl: ^0.18.0
  flutter_launcher_icons: 0.11.0
  nik_validator: 1.1.2
  shared_preferences: 2.0.15
  overlay_support: 2.1.0
  keyboard_dismisser: 2.0.1
  glass: 1.0.1+1
  indonesia: 1.0.1
  map: 1.3.5+1
  latlng: 0.2.0
  http: 0.13.5
  google_mobile_ads: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/gender/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/ktp-checker-transparent-background.png"
  image_path_android: "assets/ktp-checker-white-background.png"
  image_path_ios: "assets/ktp-checker-white-background.png"